INSERT INTO public.days_of_week (id, name_en, name_de, name_fr) VALUES 
(0, 'Monday', 'Montag', 'Lundi'),
(1, 'Tuesday', 'Dienstag', 'Mardi'),
(2, 'Wednesday', 'Mittwoch', 'Mercredi'),
(3, 'Thursday', 'Donnerstag', 'Jeudi'),
(4, 'Friday', 'Freitag', 'Vendredi'),
(5, 'Saturday', 'Samstag', 'Samedi'),
(6, 'Sunday', 'Sonntag', 'Dimanche');

INSERT INTO public.muscles (id, name_en, name_de, name_fr, description_en, description_de, description_fr) VALUES
(1, 'Abdominals', 'Bauchmuskeln', 'Abdominaux', 'The abdominal muscles are located between the ribs and the pelvis on the front of the body. They support the trunk, allow movement and hold organs in place by regulating internal abdominal pressure.', 'Die Bauchmuskeln befinden sich zwischen den Rippen und dem Becken auf der Vorderseite des Körpers. Sie stützen den Rumpf, ermöglichen Bewegungen und halten Organe an Ort und Stelle, indem sie den internen Bauchdruck regulieren.', 'Les muscles abdominaux sont situés entre les côtes et le bassin à l''avant du corps. Ils soutiennent le tronc, permettent le mouvement et maintiennent les organes en place en régulant la pression abdominale interne.'),
(2, 'Adductors', 'Adduktoren', 'Adducteurs', 'The adductors are a group of muscles located on the inside of the thigh. They are responsible for the adduction of the leg, i.e. the movement of the leg towards the body.', 'Die Adduktoren sind eine Gruppe von Muskeln, die sich an der Innenseite des Oberschenkels befinden. Sie sind für die Adduktion des Beins, d.h. die Bewegung des Beins zum Körper hin, verantwortlich.', 'Les adducteurs sont un groupe de muscles situés à l''intérieur de la cuisse. Ils sont responsables de l''adduction de la jambe, c''est-à-dire du mouvement de la jambe vers le corps.'),
(3, 'Biceps', 'Bizeps', 'Biceps', 'The biceps are a muscle group located on the front of the upper arm. They are responsible for flexing the arm at the elbow joint and rotating the forearm.', 'Der Bizeps ist eine Muskelgruppe, die sich auf der Vorderseite des Oberarms befindet. Sie ist für das Beugen des Arms am Ellenbogengelenk und das Drehen des Unterarms verantwortlich.', 'Les biceps sont un groupe de muscles situés à l''avant du bras. Ils sont responsables de la flexion du bras au niveau de l''articulation du coude et de la rotation de l''avant-bras à l''intérieur.'),
(4, 'Calves', 'Waden', 'Mollets', 'The calf muscles are located on the back of the lower leg. They are responsible for the plantar flexion of the foot, i.e. the movement of the foot away from the body.', 'Die Wadenmuskeln befinden sich auf der Rückseite des Unterschenkels. Sie sind für die Plantarflexion des Fußes, d.h. die Bewegung des Fußes vom Körper weg, verantwortlich.', 'Les muscles du mollet sont situés à l''arrière de la jambe inférieure. Ils sont responsables de la flexion plantaire du pied, c''est-à-dire du mouvement du pied vers l''extérieur du corps.'),
(5, 'Chest', 'Brust', 'Poitrine', 'The chest muscles are located on the front of the upper body. They are responsible for the adduction and internal rotation of the arm, i.e. the movement of the arm towards the body and the rotation of the arm inwards.', 'Die Brustmuskeln befinden sich auf der Vorderseite des Oberkörpers. Sie sind für die Adduktion und Innenrotation des Arms, d.h. die Bewegung des Arms zum Körper hin und die Drehung des Arms nach innen, verantwortlich.', 'Les muscles de la poitrine sont situés à l''avant du corps. Ils sont responsables de l''adduction et de la rotation interne du bras, c''est-à-dire du mouvement du bras vers le corps et de la rotation du bras vers l''intérieur.'),
(6, 'Forearms', 'Unterarme', 'Avant-bras', 'The forearm muscles are located on the front of the lower arm. They are responsible for flexing the wrist and fingers.', 'Die Unterarmmuskeln befinden sich auf der Vorderseite des Unterarms. Sie sind für das Beugen des Handgelenks und der Finger verantwortlich.', 'Les muscles de l''avant-bras sont situés à l''avant du bras inférieur. Ils sont responsables de la flexion du poignet et des doigts.'),
(7, 'Glutes', 'Gesäß', 'Fessiers', 'The gluteal muscles are located on the back of the pelvis. They are responsible for the extension and external rotation of the thigh, i.e. the movement of the thigh away from the body and the rotation of the thigh outwards.', 'Die Gesäßmuskeln befinden sich auf der Rückseite des Beckens. Sie sind für die Streckung und Außenrotation des Oberschenkels, d.h. die Bewegung des Oberschenkels vom Körper weg und die Drehung des Oberschenkels nach außen, verantwortlich.', 'Les muscles fessiers sont situés à l''arrière du bassin. Ils sont responsables de l''extension et de la rotation externe de la cuisse, c''est-à-dire du mouvement de la cuisse vers l''extérieur du corps et de la rotation de la cuisse vers l''extérieur.'),
(8, 'Hamstrings', 'Beinbeuger', 'Ischio-jambiers', 'The hamstrings are a group of muscles located on the back of the thigh. They are responsible for the flexion of the leg at the knee joint and the extension of the thigh at the hip joint.', 'Die Beinbeuger sind eine Gruppe von Muskeln, die sich auf der Rückseite des Oberschenkels befinden. Sie sind für die Beugung des Beins am Kniegelenk und die Streckung des Oberschenkels am Hüftgelenk verantwortlich.', 'Les ischio-jambiers sont un groupe de muscles situés à l''arrière de la cuisse. Ils sont responsables de la flexion de la jambe au niveau de l''articulation du genou et de l''extension de la cuisse au niveau de l''articulation de la hanche.'),
(9, 'Lats', 'Latissimus', 'Grand dorsal', 'The latissimus dorsi is a muscle located on the back of the upper body. It is responsible for the adduction and internal rotation of the arm, i.e. the movement of the arm towards the body and the rotation of the arm inwards.', 'Der Latissimus dorsi ist ein Muskel, der sich auf der Rückseite des Oberkörpers befindet. Er ist für die Adduktion und Innenrotation des Arms, d.h. die Bewegung des Arms zum Körper hin und die Drehung des Arms nach innen verantwortlich.', 'Le grand dorsal est un muscle situé à l''arrière du corps. Il est responsable de l''adduction et de la rotation interne du bras, c''est-à-dire du mouvement du bras vers le corps et de la rotation du bras vers l''intérieur.'),
(10, 'Lower Back', 'Unterer Rücken', 'Bas du dos', 'The lower back muscles are located on the back of the lower body. They are responsible for the extension and lateral flexion of the spine, i.e. the movement of the spine away from the body and the bending of the spine to the side.', 'Die unteren Rückenmuskeln befinden sich auf der Rückseite des unteren Körpers. Sie sind für die Streckung und laterale Beugung der Wirbelsäule, d.h. die Bewegung der Wirbelsäule vom Körper weg und die Beugung der Wirbelsäule zur Seite, verantwortlich.', 'Les muscles du bas du dos sont situés à l''arrière du bas du corps. Ils sont responsables de l''extension et de la flexion latérale de la colonne vertébrale, c''est-à-dire du mouvement de la colonne vertébrale vers l''extérieur du corps et de la flexion de la colonne vertébrale sur le côté.'),
(11, 'Middle Back', 'Mittlerer Rücken', 'Milieu du dos', 'The middle back muscles are located on the back of the middle body. They are responsible for the extension and lateral flexion of the spine, i.e. the movement of the spine away from the body and the bending of the spine to the side.', 'Die mittleren Rückenmuskeln befinden sich auf der Rückseite des mittleren Körpers. Sie sind für die Streckung und laterale Beugung der Wirbelsäule, d.h. die Bewegung der Wirbelsäule vom Körper weg und die Beugung der Wirbelsäule zur Seite, verantwortlich.', 'Les muscles du milieu du dos sont situés à l''arrière du milieu du corps. Ils sont responsables de l''extension et de la flexion latérale de la colonne vertébrale, c''est-à-dire du mouvement de la colonne vertébrale vers l''extérieur du corps et de la flexion de la colonne vertébrale sur le côté.'),
(12, 'Neck', 'Nacken', 'Cou', 'The neck muscles are located on the back of the upper body. They are responsible for the extension and lateral flexion of the spine, i.e. the movement of the spine away from the body and the bending of the spine to the side.', 'Die Nackenmuskeln befinden sich auf der Rückseite des Oberkörpers. Sie sind für die Streckung und laterale Beugung der Wirbelsäule, d.h. die Bewegung der Wirbelsäule vom Körper weg und die Beugung der Wirbelsäule zur Seite, verantwortlich.', 'Les muscles du cou sont situés à l''arrière du corps. Ils sont responsables de l''extension et de la flexion latérale de la colonne vertébrale, c''est-à-dire du mouvement de la colonne vertébrale vers l''extérieur du corps et de la flexion de la colonne vertébrale sur le côté.'),
(13, 'Quadriceps', 'Quadrizeps', 'Quadriceps', 'The quadriceps are a group of muscles located on the front of the thigh. They are responsible for the extension of the leg at the knee joint and the flexion of the thigh at the hip joint.', 'Die Quadrizeps sind eine Gruppe von Muskeln, die sich auf der Vorderseite des Oberschenkels befinden. Sie sind für die Streckung des Beins am Kniegelenk und die Beugung des Oberschenkels am Hüftgelenk verantwortlich.', 'Les quadriceps sont un groupe de muscles situés à l''avant de la cuisse. Ils sont responsables de l''extension de la jambe au niveau de l''articulation du genou et de la flexion de la cuisse au niveau de l''articulation de la hanche.'),
(14, 'Shoulders', 'Schultern', 'Épaules', 'The shoulder muscles are located on the upper body. They are responsible for the adduction and internal rotation of the arm, i.e. the movement of the arm towards the body and the rotation of the arm inwards.', 'Die Schultermuskeln befinden sich auf dem Oberkörper. Sie sind für die Adduktion und Innenrotation des Arms, d.h. die Bewegung des Arms zum Körper hin und die Drehung des Arms nach innen, verantwortlich.', 'Les muscles des épaules sont situés sur le haut du corps. Ils sont responsables de l''adduction et de la rotation interne du bras, c''est-à-dire du mouvement du bras vers le corps et de la rotation du bras vers l''intérieur.'),
(15, 'Traps', 'Trapezius', 'Trapèzes', 'The trapezius is a muscle located on the upper body. It is responsible for the elevation and retraction of the shoulder blades, i.e. the movement of the shoulder blades upwards and towards the spine.', 'Der Trapezius ist ein Muskel, der sich auf dem Oberkörper befindet. Er ist für die Elevation und Retraktion der Schulterblätter, d.h. die Bewegung der Schulterblätter nach oben und zur Wirbelsäule hin, verantwortlich.', 'Le trapèze est un muscle situé sur le haut du corps. Il est responsable de l''élévation et de la rétraction des omoplates, c''est-à-dire du mouvement des omoplates vers le haut et vers la colonne vertébrale.'),
(16, 'Triceps', 'Trizeps', 'Triceps', 'The triceps are a muscle group located on the back of the upper arm. They are responsible for the extension of the arm at the elbow joint.', 'Der Trizeps ist eine Muskelgruppe, die sich auf der Rückseite des Oberarms befindet. Sie ist für die Streckung des Arms am Ellenbogengelenk verantwortlich.', 'Les triceps sont un groupe de muscles situés à l''arrière du bras. Ils sont responsables de l''extension du bras au niveau de l''articulation du coude.'),
(17, 'Upper Back', 'Oberer Rücken', 'Haut du dos', 'The upper back muscles are located on the back of the upper body. They are responsible for the extension and lateral flexion of the spine, i.e. the movement of the spine away from the body and the bending of the spine to the side.', 'Die oberen Rückenmuskeln befinden sich auf der Rückseite des Oberkörpers. Sie sind für die Streckung und laterale Beugung der Wirbelsäule, d.h. die Bewegung der Wirbelsäule vom Körper weg und die Beugung der Wirbelsäule zur Seite, verantwortlich.', 'Les muscles du haut du dos sont situés à l''arrière du haut du corps. Ils sont responsables de l''extension et de la flexion latérale de la colonne vertébrale, c''est-à-dire du mouvement de la colonne vertébrale vers l''extérieur du corps et de la flexion de la colonne vertébrale sur le côté.');

INSERT INTO public.exercises (name_en, name_de, name_fr, description_en, description_de, description_fr, execution_en, execution_de, execution_fr, muscles, ressource_name) VALUES
('Deadlift', 'Kreuzheben', 'Soulevé de terre',
 'The deadlift is a compound exercise that trains the muscles of the lower back, glutes, hamstrings, quadriceps, calves, forearms, traps and abdominals. It is performed by lifting a barbell from the floor to the hips.',
 'Das Kreuzheben ist eine Verbundübung, die die Muskeln des unteren Rückens, der Gesäßmuskeln, der Beinbeuger, der Quadrizeps, der Wadenmuskeln, der Unterarme, des Trapezius und der Bauchmuskeln trainiert. Es wird ausgeführt, indem eine Langhantel vom Boden zu den Hüften gehoben wird.',
 'Le soulevé de terre est un exercice composé qui entraîne les muscles du bas du dos, des fessiers, des ischio-jambiers, des quadriceps, des mollets, des avant-bras, des trapèzes et des abdominaux. Il est réalisé en soulevant une barre du sol jusqu''aux hanches.',
 'Stand with your feet shoulder-width apart and your toes pointing slightly outwards. Bend down and grab the barbell with a shoulder-width overhand grip. Keep your back straight and your head in a neutral position. Lift the barbell by extending your knees and hips. Keep your arms straight and your back straight. Lift the barbell until you are standing upright. Lower the barbell by bending your knees and hips. Keep your arms straight and your back straight. Lower the barbell until it touches the floor. Repeat.',
 'Stellen Sie sich mit den Füßen schulterbreit auseinander und den Zehen leicht nach außen zeigend hin. Beugen Sie sich nach unten und greifen Sie die Langhantel mit einem schulterbreiten Obergriff. Halten Sie Ihren Rücken gerade und Ihren Kopf in einer neutralen Position. Heben Sie die Langhantel, indem Sie Ihre Knie und Hüften strecken. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Heben Sie die Langhantel, bis Sie aufrecht stehen. Senken Sie die Langhantel, indem Sie Ihre Knie und Hüften beugen. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Senken Sie die Langhantel, bis sie den Boden berührt. Wiederholen Sie.',
 'Placez-vous les pieds écartés à la largeur des épaules et les orteils légèrement tournés vers l''extérieur. Penchez-vous et saisissez la barre avec une prise supérieure à la largeur des épaules. Gardez le dos droit et la tête dans une position neutre. Soulevez la barre en étendant vos genoux et vos hanches. Gardez les bras tendus et le dos droit. Soulevez la barre jusqu''à ce que vous soyez debout. Abaissez la barre en pliant vos genoux et vos hanches. Gardez les bras tendus et le dos droit. Abaissez la barre jusqu''à ce qu''elle touche le sol. Répétez.',
 ARRAY[8,7,10,15],
 'deadlift'
 ),
('Bench Press', 'Bankdrücken', 'Développé couché',
 'The bench press is a compound exercise that trains the muscles of the chest, shoulders, triceps and abdominals. It is performed by lifting a barbell from the chest to the arms.',
 'Das Bankdrücken ist eine Verbundübung, die die Muskeln der Brust, der Schultern, der Trizeps und der Bauchmuskeln trainiert. Es wird ausgeführt, indem eine Langhantel von der Brust zu den Armen gehoben wird.',
 'Le développé couché est un exercice composé qui entraîne les muscles de la poitrine, des épaules, des triceps et des abdominaux. Il est réalisé en soulevant une barre de la poitrine aux bras.',
 'Lie on a bench with your feet flat on the floor. Grab the barbell with a shoulder-width overhand grip. Keep your back straight and your head in a neutral position. Lift the barbell by extending your arms. Keep your arms straight and your back straight. Lift the barbell until your arms are fully extended. Lower the barbell by bending your arms. Keep your arms straight and your back straight. Lower the barbell until it touches your chest. Repeat.',
 'Legen Sie sich auf eine Bank mit den Füßen flach auf dem Boden. Greifen Sie die Langhantel mit einem schulterbreiten Obergriff. Halten Sie Ihren Rücken gerade und Ihren Kopf in einer neutralen Position. Heben Sie die Langhantel, indem Sie Ihre Arme strecken. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Heben Sie die Langhantel, bis Ihre Arme vollständig gestreckt sind. Senken Sie die Langhantel, indem Sie Ihre Arme beugen. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Senken Sie die Langhantel, bis sie Ihre Brust berührt. Wiederholen Sie.',
 'Allongez-vous sur un banc avec les pieds à plat sur le sol. Saisissez la barre avec une prise supérieure à la largeur des épaules. Gardez le dos droit et la tête dans une position neutre. Soulevez la barre en tendant les bras. Gardez les bras tendus et le dos droit. Soulevez la barre jusqu''à ce que vos bras soient complètement tendus. Abaissez la barre en pliant les bras. Gardez les bras tendus et le dos droit. Abaissez la barre jusqu''à ce qu''elle touche votre poitrine. Répétez.',
 ARRAY[5,16,14],
 'barbell_bench_press'
),
('Squat', 'Kniebeugen', 'Squat',
 'The squat is a compound exercise that trains the muscles of the glutes, quadriceps, hamstrings, calves, abdominals and lower back. It is performed by lifting a barbell from the floor to the hips.',
 'Die Kniebeuge ist eine Verbundübung, die die Muskeln der Gesäßmuskeln, des Quadrizeps, der Beinbeuger, der Wadenmuskeln, der Bauchmuskeln und des unteren Rückens trainiert. Sie wird ausgeführt, indem eine Langhantel vom Boden zu den Hüften gehoben wird.',
 'Le squat est un exercice composé qui entraîne les muscles des fessiers, des quadriceps, des ischio-jambiers, des mollets, des abdominaux et du bas du dos. Il est réalisé en soulevant une barre du sol jusqu''aux hanches.',
 'Stand with your feet shoulder-width apart and your toes pointing slightly outwards. Bend down and grab the barbell with a shoulder-width overhand grip. Keep your back straight and your head in a neutral position. Lift the barbell by extending your knees and hips. Keep your arms straight and your back straight. Lift the barbell until you are standing upright. Lower the barbell by bending your knees and hips. Keep your arms straight and your back straight. Lower the barbell until it touches the floor. Repeat.',
 'Stellen Sie sich mit den Füßen schulterbreit auseinander und den Zehen leicht nach außen zeigend hin. Beugen Sie sich nach unten und greifen Sie die Langhantel mit einem schulterbreiten Obergriff. Halten Sie Ihren Rücken gerade und Ihren Kopf in einer neutralen Position. Heben Sie die Langhantel, indem Sie Ihre Knie und Hüften strecken. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Heben Sie die Langhantel, bis Sie aufrecht stehen. Senken Sie die Langhantel, indem Sie Ihre Knie und Hüften beugen. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Senken Sie die Langhantel, bis sie den Boden berührt. Wiederholen Sie.',
 'Placez-vous les pieds écartés à la largeur des épaules et les orteils légèrement tournés vers l''extérieur. Penchez-vous et saisissez la barre avec une prise supérieure à la largeur des épaules. Gardez le dos droit et la tête dans une position neutre. Soulevez la barre en étendant vos genoux et vos hanches. Gardez les bras tendus et le dos droit. Soulevez la barre jusqu''à ce que vous soyez debout. Abaissez la barre en pliant vos genoux et vos hanches. Gardez les bras tendus et le dos droit. Abaissez la barre jusqu''à ce qu''elle touche le sol. Répétez.',
 ARRAY[13,8,7,10],
 'back_squats'),
('Overhead Press', 'Schulterdrücken', 'Développé militaire',
 'The overhead press is a compound exercise that trains the muscles of the shoulders, triceps and abdominals. It is performed by lifting a barbell from the shoulders to the arms.',
 'Das Schulterdrücken ist eine Verbundübung, die die Muskeln der Schultern, des Trizeps und der Bauchmuskeln trainiert. Es wird ausgeführt, indem eine Langhantel von den Schultern zu den Armen gehoben wird.',
 'Le développé militaire est un exercice composé qui entraîne les muscles des épaules, des triceps et des abdominaux. Il est réalisé en soulevant une barre des épaules aux bras.',
 'Stand with your feet shoulder-width apart and your toes pointing slightly outwards. Bend down and grab the barbell with a shoulder-width overhand grip. Keep your back straight and your head in a neutral position. Lift the barbell by extending your arms. Keep your arms straight and your back straight. Lift the barbell until your arms are fully extended. Lower the barbell by bending your arms. Keep your arms straight and your back straight. Lower the barbell until it touches your shoulders. Repeat.',
 'Stellen Sie sich mit den Füßen schulterbreit auseinander und den Zehen leicht nach außen zeigend hin. Beugen Sie sich nach unten und greifen Sie die Langhantel mit einem schulterbreiten Obergriff. Halten Sie Ihren Rücken gerade und Ihren Kopf in einer neutralen Position. Heben Sie die Langhantel, indem Sie Ihre Arme strecken. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Heben Sie die Langhantel, bis Ihre Arme vollständig gestreckt sind. Senken Sie die Langhantel, indem Sie Ihre Arme beugen. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Senken Sie die Langhantel, bis sie Ihre Schultern berührt. Wiederholen Sie.',
 'Placez-vous les pieds écartés à la largeur des épaules et les orteils légèrement tournés vers l''extérieur. Penchez-vous et saisissez la barre avec une prise supérieure à la largeur des épaules. Gardez le dos droit et la tête dans une position neutre. Soulevez la barre en tendant les bras. Gardez les bras tendus et le dos droit. Soulevez la barre jusqu''à ce que vos bras soient complètement tendus. Abaissez la barre en pliant les bras. Gardez les bras tendus et le dos droit. Abaissez la barre jusqu''à ce qu''elle touche vos épaules. Répétez.',
 ARRAY[14,16,17],
 'standing_barbell_military_press'),
('Pull Up', 'Klimmzug', 'Traction',
 'The pull up is a compound exercise that trains the muscles of the back, shoulders, biceps and abdominals. It is performed by lifting the body from a hanging position to a position above the bar.',
 'Der Klimmzug ist eine Verbundübung, die die Muskeln des Rückens, der Schultern, des Bizeps und der Bauchmuskeln trainiert. Er wird ausgeführt, indem der Körper von einer hängenden Position in eine Position über der Stange gehoben wird.',
 'La traction est un exercice composé qui entraîne les muscles du dos, des épaules, des biceps et des abdominaux. Il est réalisé en soulevant le corps d''une position suspendue à une position au-dessus de la barre.',
 'Grab the bar with a shoulder-width overhand grip. Keep your arms straight and your back straight. Lift your body by bending your arms. Keep your arms straight and your back straight. Lift your body until your chin is above the bar. Lower your body by extending your arms. Keep your arms straight and your back straight. Lower your body until your arms are fully extended. Repeat.',
 'Greifen Sie die Stange mit einem schulterbreiten Obergriff. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Heben Sie Ihren Körper, indem Sie Ihre Arme beugen. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Heben Sie Ihren Körper, bis Ihr Kinn über der Stange ist. Senken Sie Ihren Körper, indem Sie Ihre Arme strecken. Halten Sie Ihre Arme gerade und Ihren Rücken gerade. Senken Sie Ihren Körper, bis Ihre Arme vollständig gestreckt sind. Wiederholen Sie.',
 'Saisissez la barre avec une prise supérieure à la largeur des épaules. Gardez les bras tendus et le dos droit. Soulevez votre corps en pliant les bras. Gardez les bras tendus et le dos droit. Soulevez votre corps jusqu''à ce que votre menton soit au-dessus de la barre. Abaissez votre corps en tendant les bras. Gardez les bras tendus et le dos droit. Abaissez votre corps jusqu''à ce que vos bras soient complètement tendus. Répétez.',
 ARRAY[9,3,17],
 'wide_grip_pull_up'),
(
  'Leg Press', 
  'Beinpresse', 
  'Presse à cuisses', 
  'The leg press is a weight training exercise in which the individual pushes a weight or resistance away from them using their legs. It is typically performed on a leg press machine.',
  'Die Beinpresse ist eine Krafttrainingsübung, bei der die Person ein Gewicht oder einen Widerstand mit den Beinen von sich wegdrückt. Sie wird typischerweise an einer Beinpresse-Maschine durchgeführt.',
  'La presse à jambes est un exercice de musculation où l''individu repousse un poids ou une résistance avec ses jambes. Il se fait généralement sur une machine de presse à jambes.',
  'Sit on the leg press machine with feet flat on the platform. Push the platform away by extending your legs, then return to the starting position with controlled movement.', 
  'Setzen Sie sich in die Beinpresse-Maschine mit flachen Füßen auf der Plattform. Drücken Sie die Plattform weg, indem Sie Ihre Beine strecken, und kehren Sie dann kontrolliert in die Ausgangsposition zurück.', 
  'Asseyez-vous sur la machine avec les pieds à plat sur la plateforme. Poussez la plateforme en étendant vos jambes, puis revenez en position initiale de manière contrôlée.', 
  ARRAY[13,7,8], 
  'leg_press'
),
(
  'Lat Pulldown', 
  'Latziehen', 
  'Tirage vertical', 
  'The lat pulldown is an exercise for the back muscles where you pull a weighted bar down towards your chest. It''s usually performed on a cable machine.', 
  'Das Latziehen ist eine Übung für die Rückenmuskulatur, bei der eine gewichtete Stange in Richtung Brust gezogen wird. Es wird normalerweise an einer Kabelmaschine durchgeführt.', 
  'Le tirage latéral est un exercice pour les muscles du dos où vous tirez une barre lestée vers votre poitrine. Il se fait généralement sur une machine à câbles.', 
  'Sit at the cable machine with your hands gripping the bar wider than shoulder-width. Pull the bar down to your chest, then slowly let it rise back up.', 
  'Setzen Sie sich an die Kabelmaschine, greifen Sie die Stange weiter als schulterbreit. Ziehen Sie die Stange zu Ihrer Brust und lassen Sie sie langsam wieder hochgehen.', 
  'Asseyez-vous à la machine à câbles, les mains écartées plus larges que les épaules sur la barre. Tirez la barre vers votre poitrine, puis laissez-la remonter lentement.', 
  ARRAY[9,3,11], 
  'wide_grip_lat_pulldown'
),
(
  'Tricep Dips', 
  'Trizeps Dips', 
  'Dips pour Triceps', 
  'Tricep dips are a bodyweight exercise that targets the triceps. They involve lowering and raising your body by bending and straightening your arms on parallel bars or a bench.', 
  'Trizeps-Dips sind eine Körpergewichtsübung, die sich auf die Trizeps konzentriert. Sie beinhalten das Senken und Heben des Körpers durch Beugen und Strecken der Arme auf Parallelstangen oder einer Bank.', 
  'Les dips pour les triceps sont un exercice au poids du corps qui cible les triceps. Ils impliquent d''abaisser et de soulever votre corps en pliant et en tendant vos bras sur des barres parallèles ou un banc.', 
  'Grip the parallel bars or bench and support your body. Lower your body by bending your elbows until they''re at 90 degrees, then press back up to the start.', 
  'Greifen Sie die Parallelstangen oder Bank und stützen Sie Ihren Körper. Senken Sie Ihren Körper, indem Sie Ihre Ellenbogen beugen, bis sie einen Winkel von 90 Grad erreichen, dann drücken Sie sich zurück in den Start.', 
  'Saisissez les barres parallèles ou le banc et soutenez votre corps. Abaissez votre corps en pliant vos coudes jusqu''à 90 degrés, puis poussez-vous en arrière au départ.', 
  ARRAY[16], 
  'triceps_dips'
),
(
  'Russian Twists', 
  'Russische Drehungen', 
  'Twists Russes', 
  'Russian twists are a core exercise where you sit on the ground with your legs bent, lean back slightly, and twist your torso from side to side, often holding a weight.', 
  'Russische Drehungen sind eine Kernübung, bei der man sich mit gebeugten Beinen auf den Boden setzt, sich leicht zurücklehnt und den Oberkörper von einer Seite zur anderen dreht, oft unter Haltung eines Gewichts.', 
  'Les torsions russes sont un exercice pour les muscles centraux où vous vous asseyez au sol avec les jambes pliées, vous penchez légèrement en arrière et tournez votre torse d''un côté à l''autre, souvent en tenant un poids.', 
  'Sit on the floor, lean back slightly, lift your feet if possible, and twist your torso to touch the ground beside you alternately with or without a weight.', 
  'Setzen Sie sich auf den Boden, lehnen Sie sich leicht zurück, heben Sie Ihre Füße, wenn möglich, und drehen Sie Ihren Oberkörper abwechselnd zur Seite, mit oder ohne Gewicht.', 
  'Asseyez-vous sur le sol, penchez-vous légèrement en arrière, levez vos pieds si possible, et tournez votre torse pour toucher alternativement le sol à côté de vous avec ou sans poids.', 
  ARRAY[1], 
  'russian_twists'
),
(
  'Facepulls', 
  'Facepulls', 
  'Tirage Visage', 
  'Facepulls are a shoulder and upper back exercise where you pull a cable towards your face, keeping your hands apart and elbows high. It''s usually done with a rope attachment on a cable machine.',
  'Facepulls sind eine Schulter- und Oberkörperübung, bei der Sie ein Kabel mit gespreizten Händen und hohen Ellenbogen zu Ihrem Gesicht ziehen. Sie wird normalerweise mit einem Seilansatz an einer Kabelmaschine durchgeführt.',
  'Les facepulls sont un exercice pour les épaules et le haut du dos où vous tirez un câble vers votre visage, en gardant les mains écartées et les coudes hauts. Cela se fait généralement avec une corde attachée à une machine à câbles.',
  'Stand facing the cable machine, grip the rope with both hands. Pull the rope towards your face while splitting the rope and pinching shoulder blades together.', 
  'Stehen Sie der Kabelmaschine gegenüber, greifen Sie das Seil mit beiden Händen. Ziehen Sie das Seil zu Ihrem Gesicht, während Sie das Seil teilen und die Schulterblätter zusammenziehen.', 
  'Tenez-vous face à la machine à câbles, saisissez la corde avec les deux mains. Tirez la corde vers votre visage en écartant la corde et en rapprochant les omoplates.', 
  ARRAY[11, 14], 
  'face_pulls'
),
(
  'Biceps Curls', 
  'Bizeps Curls', 
  'Curls Biceps', 
  'Biceps curls are a strength exercise targeting the biceps. They involve lifting a weight, typically dumbbells or a barbell, through curling the forearms towards the shoulders.', 
  'Bizeps-Curls sind eine Kraftübung, die auf die Bizeps abzielt. Sie beinhalten das Heben eines Gewichts, typischerweise Hanteln oder eine Langhantel, durch das Krümmen der Unterarme in Richtung der Schultern.', 
  'Les curls de biceps sont un exercice de renforcement ciblant les biceps. Ils impliquent de soulever un poids, généralement des haltères ou une barre, en fléchissant les avant-bras vers les épaules.', 
  'Stand with feet shoulder-width apart, holding weights at your sides. Curl the weights towards your shoulders, keeping your elbows stationary, then lower them back down.', 
  'Stehen Sie schulterbreit auseinander, Gewichte an Ihren Seiten. Krümmen Sie die Gewichte zu Ihren Schultern, indem Sie Ihre Ellenbogen stationär halten, und senken Sie sie dann wieder ab.', 
  'Tenez-vous debout, les pieds écartés à la largeur des épaules, les poids sur vos côtés. Fléchissez les poids vers vos épaules en gardant vos coudes immobiles, puis abaissez-les.', 
  ARRAY[3], 
  'dumbbell_curls'
),
(
  'T-Bar Rows', 
  'T-Bar Rows', 
  'Rowing à la T-bar', 
  'T-Bar rows are a compound exercise targeting the back muscles. The movement involves pulling a T-bar loaded with weight towards your chest while bent over.', 
  'T-Bar-Rudern ist eine komplexe Übung, die auf die Rückenmuskulatur abzielt. Die Bewegung beinhaltet das Ziehen einer mit Gewichten beladenen T-Stange in Richtung Brust, während man sich nach vorne beugt.', 
  'Les rows à la T-bar sont un exercice composé ciblant les muscles du dos. Le mouvement consiste à tirer une T-bar chargée de poids vers votre poitrine en se penchant en avant.', 
  'Stand straddling the T-bar, bend forward at the hips, grip the handle. Pull the weight towards your chest, then lower it back to the start.', 
  'Stehen Sie über die T-Stange, beugen Sie sich an der Hüfte nach vorne, greifen Sie den Griff. Ziehen Sie das Gewicht zu Ihrer Brust und senken Sie es dann wieder zum Start.', 
  'Tenez-vous debout en chevauchant la barre en T, penchez-vous en avant au niveau des hanches, saisissez la poignée. Tirez le poids vers votre poitrine, puis abaissez-le au départ.', 
  ARRAY[11, 9], 
  't_bar_row'
),
(
    'Shrugs', 
    'Schulterheben', 
    'Haussements d’épaules', 
    'Shrugs are an exercise targeting the trapezius muscles in the upper back and neck. They involve raising the shoulders towards the ears, usually holding dumbbells or a barbell.',
    'Schulterzucken sind eine Übung, die auf die Trapezmuskeln im oberen Rücken und Nacken abzielt. Sie beinhalten das Anheben der Schultern in Richtung der Ohren, meist unter Verwendung von Hanteln oder einer Langhantel.',
    'Les haussements d''épaules sont un exercice ciblant les muscles trapèzes du haut du dos et du cou. Ils impliquent de lever les épaules vers les oreilles, généralement en tenant des haltères ou une barre.',
    'Stand with feet shoulder-width, holding weights at your sides. Raise your shoulders towards your ears, hold briefly, then lower back down.', 
    'Stehen Sie schulterbreit, Gewichte an Ihren Seiten. Heben Sie Ihre Schultern zu Ihren Ohren, halten Sie kurz an, und senken Sie dann wieder ab.', 
    'Tenez-vous debout, les pieds écartés à la largeur des épaules, les poids sur vos côtés. Levez vos épaules vers vos oreilles, maintenez brièvement, puis abaissez-les.', 
    ARRAY[15], 
    'dumbbell_shrugs'
),
(
    'Dumbbell Lateral Raises', 
    'Seitheben', 
    'Élévations latérales aux haltères', 
    'Dumbbell lateral raises are a shoulder exercise where you lift dumbbells out to your sides with a slight bend in the elbows, raising them to shoulder height.', 
    'Seitliche Hantelheben sind eine Schulterübung, bei der Sie Hanteln mit leicht gebeugten Ellenbogen zur Seite heben, bis sie Schulterhöhe erreichen.', 
    'Les élévations latérales aux haltères sont un exercice pour les épaules où vous soulevez des haltères sur vos côtés avec un léger pli aux coudes, les élevant à la hauteur des épaules.', 
    'Stand with feet shoulder-width apart, weights at sides. Lift the weights out to the sides with a slight bend in elbows, then lower them back down.', 
    'Stehen Sie schulterbreit auseinander, Gewichte an den Seiten. Heben Sie die Gewichte seitlich mit leicht gebeugten Ellenbogen und senken Sie sie dann wieder ab.', 
    'Tenez-vous debout, les pieds écartés à la largeur des épaules, les poids sur vos côtés. Soulevez les poids sur les côtés avec un léger pli aux coudes, puis abaissez-les.', 
    ARRAY[14], 
    'dumbbell_lateral_raise'
),
(
    'Cable Crossover', 
    'Kabelzug Crosses', 
    'Crossover aux câbles', 
    'The cable crossover is a chest exercise where you pull two cables from high pulleys across your body. It targets the pectoral muscles.', 
    'Der Cable Crossover ist eine Brustübung, bei der Sie zwei Kabel von hohen Rollen über Ihren Körper ziehen. Sie zielt auf die Brustmuskeln ab.', 
    'Le crossover à câbles est un exercice pectoral où vous tirez deux câbles de poulies hautes à travers votre corps. Il cible les muscles pectoraux.', 
    'Stand between two cable towers with pulleys set high. Lean forward slightly, extend arms out to the sides, then bring your hands together in front of you.', 
    'Stehen Sie zwischen zwei Kabeltürmen mit hoch eingestellten Rollen. Lehnen Sie sich leicht vor, strecken Sie Ihre Arme zur Seite, und bringen Sie Ihre Hände vor Ihnen zusammen.', 
    'Tenez-vous entre deux tours de câble avec des poulies réglées en haut. Penchez-vous légèrement en avant, étendez les bras sur les côtés, puis amenez vos mains ensemble devant vous.', 
    ARRAY[5], 
    'standing_cable_chest_press'
),
(
    'Dumbbell Bench Press', 
    'Kurzhantelbankdrücken', 
    'Développé couché aux haltères', 
    'The dumbbell bench press is a chest exercise that involves pressing dumbbells upwards from a lying position on a bench. It targets chest, shoulders, and triceps.', 
    'Die Hantelbankdrücken ist eine Brustübung, die das Drücken von Hanteln nach oben aus einer liegenden Position auf einer Bank beinhaltet. Sie zielt auf Brust, Schultern und Trizeps ab.', 
    'Le développé couché aux haltères est un exercice pour la poitrine qui consiste à presser des haltères vers le haut depuis une position allongée sur un banc. Il cible la poitrine, les épaules et les triceps.', 
    'Lie on a bench with dumbbells in each hand. Press the weights up until your arms are straight, then lower them back to chest level.', 
    'Liegen Sie auf einer Bank mit Hanteln in jeder Hand. Drücken Sie die Gewichte nach oben, bis Ihre Arme gerade sind, und senken Sie sie dann wieder auf Brusthöhe.', 
    'Allongez-vous sur un banc avec des haltères dans chaque main. Pressez les poids vers le haut jusqu''à ce que vos bras soient tendus, puis abaissez-les au niveau de la poitrine.', 
    ARRAY[5], 
    'dumbbell_bench_press'
),
(
    'Incline Flye', 
    'Schrägbank Flye', 
    'Écarté incliné', 
    'Incline flyes are a chest exercise performed on an incline bench. You lift dumbbells in a wide arc above your chest, targeting the upper pectoral muscles.', 
    'Schrägbank-Fliegende sind eine Brustübung, die auf einer Schrägbank durchgeführt wird. Sie heben Hanteln in einem weiten Bogen über Ihrer Brust, was die oberen Brustmuskeln beansprucht.', 
    'Les écartés inclinés sont un exercice pour la poitrine réalisé sur un banc incliné. Vous soulevez des haltères dans un large arc au-dessus de votre poitrine, ciblant les muscles pectoraux supérieurs.', 
    'Lie on an incline bench with weights. Extend your arms above your chest, then open your arms wide and lower the weights to the sides, then bring them back up.', 
    'Liegen Sie auf einer Schrägbank mit Gewichten. Strecken Sie Ihre Arme über Ihrer Brust aus, öffnen Sie dann Ihre Arme weit und senken Sie die Gewichte zu den Seiten, bevor Sie sie wieder hochbringen.', 
    'Allongez-vous sur un banc incliné avec des poids. Tendez vos bras au-dessus de votre poitrine, puis ouvrez grand vos bras et abaissez les poids sur les côtés avant de les remonter.', 
    ARRAY[5], 
    'incline_dumbbell_flyes'
),
(
    'Leg Curl', 
    'Leg Curl', 
    'Flexion des jambes', 
    'Leg curls are a lower body exercise targeting the hamstrings. They involve lying face down and curling a weight towards your buttocks, typically on a leg curl machine.', 
    'Beinbeugen sind eine Unterkörperübung, die sich auf die Oberschenkelrückseite konzentriert. Sie beinhalten das Liegen auf dem Bauch und das Krümmen eines Gewichts in Richtung Gesäß, typischerweise an einer Beinbeugemaschine.', 
    'Les leg curls sont un exercice pour le bas du corps ciblant les ischio-jambiers. Ils impliquent de s''allonger face vers le bas et de courber un poids vers les fesses, généralement sur une machine à leg curls.', 
    'Lie face down on the leg curl machine. Bend your knees to pull the weight towards your buttocks, then slowly return to the starting position.', 
    'Legen Sie sich auf die Bauchseite auf die Beinbeugemaschine. Beugen Sie Ihre Knie, um das Gewicht zu Ihrem Gesäß zu ziehen, und kehren Sie dann langsam in die Ausgangsposition zurück.', 
    'Allongez-vous face contre terre sur la machine à leg curls. Pliez vos genoux pour tirer le poids vers vos fesses, puis revenez lentement en position de départ.', 
    ARRAY[8], 
    'lying_leg_curls'
),
(
    'Leg Extension', 
    'Beinstrecker', 
    'Extension des jambes', 
    'Leg extensions are a lower body exercise focusing on the quadriceps. The movement involves extending the legs against resistance, usually on a leg extension machine.', 
    'Beinstrecken sind eine Unterkörperübung, die sich auf die Quadrizeps konzentriert. Die Bewegung beinhaltet das Strecken der Beine gegen Widerstand, üblicherweise an einer Beinstreckmaschine.', 
    'Les extensions de jambe sont un exercice du bas du corps qui se concentre sur les quadriceps. Le mouvement implique d''étendre les jambes contre une résistance, généralement sur une machine à extensions de jambe.', 
    'Sit on the leg extension machine with shins under the pads. Lift the weight by extending your legs, then lower them back down.', 
    'Setzen Sie sich auf die Beinstreckmaschine mit Schienbeinen unter den Polstern. Heben Sie das Gewicht, indem Sie Ihre Beine strecken, und senken Sie sie dann wieder ab.', 
    'Asseyez-vous sur la machine à extensions de jambe avec les tibias sous les coussinets. Soulevez le poids en étendant vos jambes, puis abaissez-les.', 
    ARRAY[13], 
    'leg_extension'
),
(
    'Bulgarian Split Squat', 
    'Bulgarische Kniebeuge', 
    'Fente Bulgare', 
    'The Bulgarian split squat is a single-leg squat variation. With one foot elevated on a bench behind you, you squat down with the other leg, targeting the quadriceps and glutes.', 
    'Der Bulgarische Split-Squat ist eine Einzelbein-Kniebeugen-Variante. Mit einem Fuß erhöht auf einer Bank hinter Ihnen, beugen Sie sich mit dem anderen Bein, was die Quadrizeps und Gesäßmuskeln beansprucht.', 
    'Le squat bulgare est une variante de squat sur une jambe. Avec un pied élevé sur un banc derrière vous, vous fléchissez sur l''autre jambe, ciblant les quadriceps et les fessiers.', 
    'Stand in a lunge position with one foot on a bench behind you. Lower your body by bending your front knee, then drive back up to the start.', 
    'Stehen Sie in einer Ausfallschritt-Position mit einem Fuß auf einer Bank hinter Ihnen. Senken Sie Ihren Körper, indem Sie Ihr vorderes Knie beugen, und drücken Sie sich dann zurück in den Start.', 
    'Tenez-vous en position de fente avec un pied sur un banc derrière vous. Abaissez votre corps en pliant votre genou avant, puis poussez-vous en arrière au départ.', 
    ARRAY[13, 7], 
    'bulgarian_split_squats'
)
;