name: Run Tests, Lint, Build & Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21

    - name: Install dependencies
      run: npm ci

    - name: Run EsLint
      run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: localhost:54321

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test:unit

  e2e-test:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: localhost:54321

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev

  docker:
    runs-on: ubuntu-latest
    needs: [lint, unit-test, e2e-test]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Determine tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/-/g')
            SHORT_SHA=$(echo $GITHUB_SHA | head -c 7)
            echo "TAG=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Login to Scaleway
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.SCW_REGISTRY_NAME }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.SCW_IMAGE_NAME }}:${{ env.TAG }}

#  deploy:
#    runs-on: ubuntu-latest
#    name: Deploy on Scaleway Containers
#    needs: [docker]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Scaleway Container Deploy action
#        id: deploy
#        uses:  philibea/scaleway-containers-deploy@v1.1.0
#        with:
#          type: deploy
#          scw_access_key:  ${{ secrets.SCW_ACCESS_KEY }}
#          scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
#          scw_containers_namespace_id: ${{ secrets.SCW_CONTAINERS_NAMESPACE_ID }}
#          scw_registry: ${{ vars.SCW_IMAGE_NAME }}:latest